# -*- coding: utf-8 -*-
"""KK.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdyl83s5ma0gCOpPE01-6SJK5Bu8gTBW
"""

pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile our_application.py
# import streamlit as st
# st.write("Hello Karthi!")
# 
#

! wget -q -O - ipv4.icanhazip.com

! streamlit run our_application.py & npx localtunnel --port 8501